//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addressee.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Addressee.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Capital Territory.
        /// </summary>
        internal static string AustralianState_ACT_Long {
            get {
                return ResourceManager.GetString("AustralianState_ACT_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.
        /// </summary>
        internal static string AustralianState_ACT_Short {
            get {
                return ResourceManager.GetString("AustralianState_ACT_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jervis Bay Territory.
        /// </summary>
        internal static string AustralianState_JBT_Long {
            get {
                return ResourceManager.GetString("AustralianState_JBT_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBT.
        /// </summary>
        internal static string AustralianState_JBT_Short {
            get {
                return ResourceManager.GetString("AustralianState_JBT_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New South Wales.
        /// </summary>
        internal static string AustralianState_NSW_Long {
            get {
                return ResourceManager.GetString("AustralianState_NSW_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSW.
        /// </summary>
        internal static string AustralianState_NSW_Short {
            get {
                return ResourceManager.GetString("AustralianState_NSW_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Territory.
        /// </summary>
        internal static string AustralianState_NT_Long {
            get {
                return ResourceManager.GetString("AustralianState_NT_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT.
        /// </summary>
        internal static string AustralianState_NT_Short {
            get {
                return ResourceManager.GetString("AustralianState_NT_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queensland.
        /// </summary>
        internal static string AustralianState_QLD_Long {
            get {
                return ResourceManager.GetString("AustralianState_QLD_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QLD.
        /// </summary>
        internal static string AustralianState_QLD_Short {
            get {
                return ResourceManager.GetString("AustralianState_QLD_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Australia.
        /// </summary>
        internal static string AustralianState_SA_Long {
            get {
                return ResourceManager.GetString("AustralianState_SA_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        internal static string AustralianState_SA_Short {
            get {
                return ResourceManager.GetString("AustralianState_SA_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasmania.
        /// </summary>
        internal static string AustralianState_TAS_Long {
            get {
                return ResourceManager.GetString("AustralianState_TAS_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS.
        /// </summary>
        internal static string AustralianState_TAS_Short {
            get {
                return ResourceManager.GetString("AustralianState_TAS_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victoria.
        /// </summary>
        internal static string AustralianState_VIC_Long {
            get {
                return ResourceManager.GetString("AustralianState_VIC_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIC.
        /// </summary>
        internal static string AustralianState_VIC_Short {
            get {
                return ResourceManager.GetString("AustralianState_VIC_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Australia.
        /// </summary>
        internal static string AustralianState_WA_Long {
            get {
                return ResourceManager.GetString("AustralianState_WA_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA.
        /// </summary>
        internal static string AustralianState_WA_Short {
            get {
                return ResourceManager.GetString("AustralianState_WA_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string SupportedCountry_Australia {
            get {
                return ResourceManager.GetString("SupportedCountry_Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string SupportedCountry_Russia {
            get {
                return ResourceManager.GetString("SupportedCountry_Russia", resourceCulture);
            }
        }
    }
}
